# Generated by Django 3.1.5 on 2021-01-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210108_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandle',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
