# Generated by Django 3.1.5 on 2021-01-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210113_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=200)),
                ('slug', models.SlugField(default='', max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='sandle',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='sandle',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
