# Generated by Django 3.1.5 on 2021-01-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.ManyToManyField(related_name='sizes', to='store.Category'),
        ),
    ]
