# Generated by Django 3.1.7 on 2021-03-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210118_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandle',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
