# Generated by Django 3.1.7 on 2021-03-05 01:14

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210302_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, default='', help_text='Contact phone number', max_length=20),
        ),
    ]
